production:
  app_id: 59334
  app_key: 05a727cb51dd5bd1c402
  secret: 7ddd5a5c5220415d6ab5

development:
  app_id: 59334
  app_key: 05a727cb51dd5bd1c402
  secret: 7ddd5a5c5220415d6ab5

test:
  app_id: xxx
  app_key: xxx
  secret: xxx
